# 1. What is NumPy

NumPy (Numerical Python) is a Python library for working with numbers and mathematical operations. It provides support for large arrays and matrices, along with fast mathematical functions.

Usually more efficient in the calculations in comparison to Pandas

## Main Uses
- Performing mathematical and statistical operations
- Working with large arrays and multi-dimensional data
- Linear algebra calculations (matrices, vectors)
- Scientific computing and data processing
- Foundation for other libraries (Pandas, Scikit-learn, TensorFlow)

# 2. Importing the library 
- `import numpy as np`
- Storing the library under the shortcut `np`

In [1]:
import numpy as np

## 3. Numpy Methods

### 3.1 Numpy Array


NumPy arrays are the main data structure in NumPy for numerical computing. They store elements of the same data type, making them faster and more efficient than Python lists.

**Creating Arrays:**
- `np.array([1, 2, 3])` - from a list
  - Example: `np.array([1, 2, 3])` creates `[1 2 3]`
  - Example: `np.array([[1, 2], [3, 4]])` creates a 2D array
  - I can restrict the type of the elements ex i can defnie `np.array([1, 2, 3], dtype=np.int16)` to restrict size 
  
- `np.zeros(5)` - array of zeros
  - Example: `np.zeros(5)` creates `[0. 0. 0. 0. 0.]`
  - Example: `np.zeros((2, 3))` creates a 2x3 array of zeros
  
- `np.ones(3)` - array of ones
  - Example: `np.ones(3)` creates `[1. 1. 1.]`
  - Example: `np.ones((3, 2))` creates a 3x2 array of ones
  
- `np.arange(0, 10, 2)` - sequence with step
  - Example: `np.arange(0, 10, 2)` creates `[0 2 4 6 8]`
  - Example: `np.arange(5)` creates `[0 1 2 3 4]`
  
- `np.linspace(0, 1, 5)` - evenly spaced values
  - Example: `np.linspace(0, 1, 5)` creates `[0.   0.25 0.5  0.75 1.  ]`
  - Example: `np.linspace(0, 10, 3)` creates `[0. 5. 10.]`

**Array Properties:**
- `.shape` - Returns dimensions as a tuple
  - Example: `arr.shape` returns `(3, 4)` for a 3-row, 4-column array
  - 1D array: `(5,)`, 2D array: `(3, 4)`, 3D array: `(2, 3, 4)`
  - When `arr.shape` returns `(3, 4)`, it means:
    - An array of **3 elements**
    - Each element is an array of **4 elements**
    ```python
    [
        [1, 2, 3, 4],      # First element (array of 4)
        [5, 6, 7, 8],      # Second element (array of 4)
        [9, 10, 11, 12]    # Third element (array of 4)
    ]
  ```

- `.reshape()` - Changes the shape of an array without changing its data
  - Example: `arr.reshape(2, 6)` converts a `(12,)` array to `(2, 6)`
  - Example: `np.arange(12).reshape(3, 4)` creates:
  ```python
      [[0,  1,  2,  3],
      [4,  5,  6,  7],
      [8,  9, 10, 11]]
  ```
  - Total elements must remain the same (e.g., 12 elements can reshape to (3,4) or (2,6) or (12,))
  - Use `-1` to automatically calculate one dimension: 
    - `arr.reshape(3, -1) ` - You specify 3 rows, NumPy calculates column
    - `arr.reshape(-1, 4)` - You specify 4 columns, NumPy calculates rows  
  - **Flatten to 1D array:**
  ```python
      arr = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
      
      arr.reshape(-1)     # Shape: (6,) → [1, 2, 3, 4, 5, 6]
      arr.flatten()       # Alternative method → [1, 2, 3, 4, 5, 6]
      arr.ravel()         # Another alternative → [1, 2, 3, 4, 5, 6]
  ```
  - Note: `reshape(-1)` is most common for flattening to 1D

- `.dtype` - Returns the data type of elements
  - Example: `arr.dtype` returns `int64`, `float64`, `bool`, etc.
  - All elements must be the same type
  
- `.size` - Returns total number of elements
  - Example: For shape `(3, 4)`, `arr.size` returns `12`
  - Calculated as the product of all dimensions

- `.ndim` - Returns number of dimensions
  - Example: `arr.ndim` returns `1` for 1D, `2` for 2D, `3` for 3D arrays

**Arithmetic Operations:**
- `arr + 5` - Add 5 to every element
  - Example: `[1, 2, 3] + 5` = `[6, 7, 8]`
- `arr * 2` - Multiply every element by 2
  - Example: `[1, 2, 3] * 2` = `[2, 4, 6]`
- `arr - 3` - Subtract 3 from every element
- `arr / 2` - Divide every element by 2
- `arr ** 2` - Square every element
  - Example: `[1, 2, 3] ** 2` = `[1, 4, 9]`

**Array to Array Operations:**
- `arr1 + arr2` - Add corresponding elements
  - Example: `[1, 2, 3] + [4, 5, 6]` = `[5, 7, 9]`
- `arr1 * arr2` - Multiply corresponding elements
  - Example: `[1, 2, 3] * [2, 2, 2]` = `[2, 4, 6]`

**Mathematical Functions:**
- `np.sqrt(arr)` - Square root of each element
- `np.exp(arr)` - Exponential of each element
- `np.sin(arr)` - Sine of each element
- `np.log(arr)` - Natural logarithm of each element

**Aggregate Functions:**
- `arr.sum()` - Sum of all elements
  - Example: `[1, 2, 3].sum()` = `6`
- `arr.mean()` - Average of all elements
- `arr.max()` - Maximum value
- `arr.min()` - Minimum value
- `arr.std()` - Standard deviation

**Comparison Operations:**
- `arr > 5` - Returns boolean array
  - Example: `[3, 6, 9] > 5` = `[False, True, True]`
- `arr == 3` - Check which elements equal 3

**Key Features:**
- Support 1D, 2D, 3D, and higher dimensions
- Fast mathematical operations on entire arrays
- Indexing and slicing like Python lists
- Broadcasting for operations between different sized arrays

In [ ]:
# Creating a 1D array 
arr = np.array([1,2,3,4])
print("\n 1D Array: \n", arr)

# Arithmatic Operator *2 on 1D Array
print("\n Multiply 1D Array Elements by 2: \n", arr * 2)

# Creating a 2D array
arr2 = np.array([[1,2],[3,4]])
print("\n 2D Array: \n", arr2)

# Create array of zeros
arr3 = np.zeros(10)
print("\n Zeros Array: \n", arr3)

# Create array of ones
arr4 = np.ones(10)
print("\n Ones Array: \n", arr4)

# Create an Array With Sequence Step
# Starts at 0, ends at 10 (exclusive) step = 2
arr5 = np.arange(0,10,2)
print("\n Step Array: \n", arr5)

# Create an array of evenly spaced values 
# Start = 0, end = 1 and space-evenly by 5 (create 5 elements evenly spaced that are within the start-end range) end inclusive if it reaches the end
arr6 = np.linspace(0,1,5)
print("\n Evenly Spaced Array: \n", arr6)

# Properites - Shape of the array
arr7 = np.array([ [1,2,3],[4,5,6] ])
print("\n Shape of array \n", arr7.shape) # 2 rows, 3 columns => consits of 2 nested arrays, each of them consists of 3 elements.
# Returns a tuple (2,3) to access the  elements either arr7.shape[0] => 2 or arr7.shape[1] => 3 

# Properties - Reshape of the array 
arr8 =  np.arange(12) # array from 0,11
print("\n Array before reshape : \n",arr8 )
arr8 = arr8.reshape(3,4) # Reshape it , make the array consist of 3 rows and each row has 4 columns 
print("\n Reshpaed Array : \n",arr8 )
print("\n Size Reshpaed Array : \n",arr8.size ) # 12 elements in the array 
print(" \n Dimension of Reshaped array \n", arr8.ndim)








 1D Array: 
 [1 2 3 4]

 Multiply 1D Array Elements by 2: 
 [2 4 6 8]

 2D Array: 
 [[1 2]
 [3 4]]

 Zeros Array: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 Ones Array: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 Step Array: 
 [0 2 4 6 8]

 Evenly Spaced Array: 
 [0.   0.25 0.5  0.75 1.  ]

 Shape of array 
 (2, 3)

 Array before reshape : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshpaed Array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Size Reshpaed Array : 
 12
 
 Dimension of Reshaped array 
 2

 Operational array > 5:
 [ 6  7  8  9 10 11]


### 3.2 Numpy Arrays Indexing

In [ ]:
# Accessing Elements In the array 
arr9 = np.arange(12)

# 1. NORMAL INDEXING (positive index)
arr9[0]      # First element: 0
arr9[5]      # 6th element: 5
arr9[11]     # Last element: 11


# 2. NEGATIVE INDEXING (count from end)
arr9[-1]     # Last element: 11
arr9[-2]     # Second to last: 10
arr9[-12]    # First element: 0

# 3. RANGE/SLICING [start:stop:step]

# Basic slicing
arr9[2:5]        # Elements from index 2 to 4: [2, 3, 4]
arr9[0:3]        # First 3 elements: [0, 1, 2]
arr9[5:10]       # Index 5 to 9: [5, 6, 7, 8, 9]

# Omitting start (starts from beginning)
arr9[:5]         # First 5 elements: [0, 1, 2, 3, 4]
arr9[:3]         # [0, 1, 2]

# Omitting stop (goes to end)
arr9[5:]         # From index 5 to end: [5, 6, 7, 8, 9, 10, 11]
arr9[8:]         # [8, 9, 10, 11]

# Omitting both (entire array)
arr9[:]          # All elements: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# With step
arr9[0:10:2]     # Every 2nd element from 0 to 9: [0, 2, 4, 6, 8]
arr9[::2]        # Every 2nd element: [0, 2, 4, 6, 8, 10]
arr9[1::2]       # Every 2nd starting from index 1: [1, 3, 5, 7, 9, 11]
arr9[::3]        # Every 3rd element: [0, 3, 6, 9]

# Negative indices in slicing
arr9[-5:]        # Last 5 elements: [7, 8, 9, 10, 11]
arr9[-8:-3]      # From -8 to -4: [4, 5, 6, 7, 8]
arr9[:-3]        # All except last 3: [0, 1, 2, 3, 4, 5, 6, 7, 8]

# Negative step (reverse)
arr9[::-1]       # Reverse entire array: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
arr9[10:2:-1]    # From 10 to 3 backwards: [10, 9, 8, 7, 6, 5, 4, 3]
arr9[::-2]       # Every 2nd element reversed: [11, 9, 7, 5, 3, 1]

# Combining positive and negative
arr9[2:-2]       # From index 2 to second-to-last: [2, 3, 4, 5, 6, 7, 8, 9]
arr9[-6:8]       # [6, 7]

### 3.3 Array Operations  & Aggergate functions

In [47]:
# Conditional arrays
arr10 = np.arange(12)
print("\n Operational array (Print elements true for elems greater than 5):\n", arr10[arr10>5])
print("\n Operational array (boolean elements true for elems equal than 5):\n", arr10>5)


# Arthimatic operations 
arr11 = np.array([1,2,3])
arr12 = np.array([4,5,6])

print("\n Two Arrays added together- returns single array with elements added: \n", arr11 + arr12)
print("\n Two Arrays divided together- returns single array with elements divided: \n", arr11 / arr12)
print("\n Two Arrays multiplied together- returns single array with elements multiplied: \n", arr11 * arr12)
print("\n Array added to a constact- returns single array with result of each element + constant: \n", arr11 + 10)

# Aggergate Functions
arr13 = np.arange(12)

print("\n Print Array mean: \n", arr13.mean())
print("\n Print Array max: \n", arr13.max())
print("\n Print Array min: \n", arr13.min())
print("\n Print Array sum: \n", arr13.sum())






 Operational array (Print elements true for elems greater than 5):
 [ 6  7  8  9 10 11]

 Operational array (boolean elements true for elems equal than 5):
 [False False False False False False  True  True  True  True  True  True]

 Two Arrays added together- returns single array with elements added: 
 [5 7 9]

 Two Arrays divided together- returns single array with elements divided: 
 [0.25 0.4  0.5 ]

 Two Arrays multiplied together- returns single array with elements multiplied: 
 [ 4 10 18]

 Array added to a constact- returns single array with result of each element + constant: 
 [11 12 13]

 Print Array mean: 
 5.5

 Print Array max: 
 11

 Print Array min: 
 0

 Print Array sum: 
 66


### 3.4 Array Extra Methods


In [ ]:
# ==========================================
# RANDOM METHODS
# ==========================================

# Random integers
print("\n Random integers between 0-10 (5 elements):\n", np.random.randint(0, 10, 5))

# Random floats between 0 and 1
print("\n Random floats (3x3 array):\n", np.random.rand(3, 3))

# Random floats from normal distribution
print("\n Random normal distribution (mean=0, std=1):\n", np.random.randn(5))

# Random choice from array
arr_choice = np.array([10, 20, 30, 40, 50])
print("\n Random choice from array:\n", np.random.choice(arr_choice, 3))

# Shuffle array (in-place)
arr_shuffle = np.arange(10)
np.random.shuffle(arr_shuffle)
print("\n Shuffled array:\n", arr_shuffle)

# Set random seed for reproducibility
np.random.seed(42)
print("\n Random with seed (always same result):\n", np.random.rand(3))


# ==========================================
# ARRAY MANIPULATION METHODS
# ==========================================

arr14 = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose
print("\n Transposed array (swap rows/columns):\n", arr14.T)

# Flatten (1D)
print("\n Flattened array:\n", arr14.flatten())

# Sort
arr15 = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("\n Sorted array:\n", np.sort(arr15))

# Unique values
arr16 = np.array([1, 2, 2, 3, 3, 3, 4])
print("\n Unique values:\n", np.unique(arr16))

# Concatenate arrays
arr17 = np.array([1, 2, 3])
arr18 = np.array([4, 5, 6])
print("\n Concatenated arrays:\n", np.concatenate([arr17, arr18]))

# Stack arrays vertically
print("\n Vertically stacked:\n", np.vstack([arr17, arr18])) # Stack rows on top of each other, basically creating a 2d array

# Stack arrays horizontally
print("\n Horizontally stacked:\n", np.hstack([arr17, arr18])) # Stack side by side basically concatinate

# ==========================================
# ADVANCED INDEXING METHODS
# ==========================================

arr19 = np.arange(20)

# Where condition
print("\n Indices where elements > 10:\n", np.where(arr19 > 10))  # Returns tuple of indices where condition is True

# Replace values using where
print("\n Replace values > 10 with -1:\n", np.where(arr19 > 10, -1, arr19))  # If condition True use -1, else keep original value

# Clip values
print("\n Clip values between 5 and 15:\n", np.clip(arr19, 5, 15))  # Values < 5 become 5, values > 15 become 15

# ==========================================
# STATISTICAL METHODS
# ==========================================

arr20 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("\n Median:\n", np.median(arr20))
print("\n Standard deviation:\n", np.std(arr20))
print("\n Variance:\n", np.var(arr20))
print("\n Percentile (50th):\n", np.percentile(arr20, 50))


# ==========================================
# MATRIX OPERATIONS
# ==========================================

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication (dot product)
print("\n Matrix multiplication:\n", np.dot(mat1, mat2))
# Or using @ operator
print("\n Matrix multiplication (@):\n", mat1 @ mat2)

# Determinant
print("\n Determinant:\n", np.linalg.det(mat1))

# Inverse
print("\n Matrix inverse:\n", np.linalg.inv(mat1))

# ==========================================
# COPY VS VIEW
# ==========================================

arr22 = np.arange(5)

# View (shares memory)
arr_view = arr22.view()
arr_view[0] = 999
print("\n Original after view change:\n", arr22)  # Changed!

# Copy (independent)
arr_copy = arr22.copy()
arr_copy[1] = 888
print("\n Original after copy change:\n", arr22)  # Not changed!


 Random integers between 0-10 (5 elements):
 [4 6 9 2 6]

 Random floats (3x3 array):
 [[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]

 Random normal distribution (mean=0, std=1):
 [-0.57138017 -0.92408284 -2.61254901  0.95036968  0.81644508]

 Random choice from array:
 [20 40 40]

 Shuffled array:
 [1 8 7 5 4 9 0 3 6 2]

 Random with seed (always same result):
 [0.37454012 0.95071431 0.73199394]

 Transposed array (swap rows/columns):
 [[1 4]
 [2 5]
 [3 6]]

 Flattened array:
 [1 2 3 4 5 6]

 Sorted array:
 [1 1 2 3 4 5 6 9]

 Unique values:
 [1 2 3 4]

 Concatenated arrays:
 [1 2 3 4 5 6]

 Vertically stacked:
 [[1 2 3]
 [4 5 6]]

 Horizontally stacked:
 [1 2 3 4 5 6]

 Indices where elements > 10:
 (array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

 Replace values > 10 with -1:
 [ 0  1  2  3  4  5  6  7  8  9 10 -1 -1 -1 -1 -1 -1 -1 -1 -1]

 Clip values between 5 and 15:
 [ 5  5  5  5  5  5  6  7  8  9 10 11 1